### ISSUE TITLE
How to get a WebSocket connection from independent web page?

### ISSUE THREAD

**Issue by jkleiser** [jorishermans/dart-force-helloworld#1]
I manage to connect and send "foo" messages to the server by clicking on the "send foo" link on the index page at http://xyz.local:8080/, but I have not found out which WebSocket URI to use when I want to open a WebSocket connection from an independent web page. I have tried 'ws = new WebSocket("ws://xyz.local:8080")', but it seems there's no WebSocket server listening at that URI. If it is at all possible to connect from an independent web page, it would be useful if the server printed the URI in the log upon startup.
The broadcasting aspect is very interesting.

**Comment by jorishermans** [comment]
You want to connect to the server from another webpage without using the forceClient? Then try "ws://xyz.local:8080/ws" I think, I used a configurable path in the application. Great that you could get it working :+1:

**Comment by jkleiser** [comment]
Hi! Yes, I managed to connect using "ws://localhost:8080/ws", but sending just "foo" was probably not the smartest thing to do. I got this in the log:
Unhandled exception:
FormatException: Unexpected character at 0: 'foo'
#0      _rootHandleUncaughtError.<anonymous closure>.<anonymous closure> (dart:async/zone.dart:677)
#1      _asyncRunCallback (dart:async/schedule_microtask.dart:18)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:21)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:119)

… but anyway, this is a step in the right direction. Thanks.
